In [1]:
#Load pandas and numpy with aliasing
import pandas as pd
import numpy as np
import datetime

In [ ]:
#Reading csv file
final_df=pd.read_csv('/content/drive/MyDrive/bus-breakdowns-delays.csv', low_memory=False)
final_df.head()

In [21]:
#Check name of column
final_df.columns
#Check column types
final_df.dtypes

School_Year                        object
Busbreakdown_ID                     int64
Run_Type                           object
Bus_No                             object
Route_Number                       object
Reason                             object
Schools_Serviced                   object
Occurred_On                        object
Created_On                         object
Boro                               object
Bus_Company_Name                   object
How_Long_Delayed                   object
Number_Of_Students_On_The_Bus       int64
Has_Contractor_Notified_Schools    object
Has_Contractor_Notified_Parents    object
Have_You_Alerted_OPT               object
Informed_On                        object
Incident_Number                    object
Last_Updated_On                    object
Breakdown_or_Running_Late          object
School_Age_or_PreK                 object
dtype: object

In [17]:
#check duplicate Breakdown ID
final_df['Busbreakdown_ID'].duplicated().any()

False

In [ ]:
#Check String type
pd.unique(dirty_df['School_Year'])

array(['2015-2016', '2017-2018', '2016-2017', '2018-2019', '2022-2023',
       '2019-2020', '2021-2022', '2020-2021'], dtype=object)

In [3]:
pd.unique(dirty_df['Run_Type'])

array(['Special Ed AM Run', 'Pre-K/EI', 'General Ed AM Run',
       'General Ed Field Trip', 'Special Ed PM Run', 'General Ed PM Run',
       'Project Read PM Run', 'Special Ed Field Trip',
       'Project Read AM Run', 'Project Read Field Trip', nan],
      dtype=object)

In [ ]:
#Check null value with Run_Type column
final_df[(final_df['Run_Type'].isnull())]

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
65554,2016-2017,1311159,NaN,NI0649,K022,Late return from Field Trip,20180,12/23/2016 02:22:00 PM,12/23/2016 02:25:00 PM,Brooklyn,...,45MINS,0,Yes,Yes,No,12/23/2016 02:25:00 PM,NaN,12/23/2016 02:42:04 PM,Running Late,School-Age
130237,2017-2018,1382111,NaN,1430,M437,Heavy Traffic,"05079,05440",10/30/2017 07:52:00 AM,10/30/2017 07:54:00 AM,Manhattan,...,16-30 Min,4,Yes,Yes,Yes,10/30/2017 07:54:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
178090,2015-2016,1273634,NaN,404,P598,Flat Tire,26704,06/06/2016 11:05:00 AM,06/06/2016 11:07:00 AM,Queens,...,NaN,0,Yes,Yes,No,06/06/2016 11:07:00 AM,NaN,06/06/2016 11:07:14 AM,Breakdown,School-Age
493618,2021-2022,1703387,NaN,1258,Q141,Heavy Traffic,28010,02/18/2022 07:20:00 AM,02/18/2022 07:22:00 AM,Queens,...,31-45 Min,1,Yes,Yes,Yes,02/18/2022 07:22:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
523487,2022-2023,1767897,NaN,4803,K761,Heavy Traffic,"21007,21239,21370",11/16/2022 07:44:00 AM,11/16/2022 07:45:00 AM,Brooklyn,...,31-45 Min,0,Yes,Yes,Yes,11/16/2022 07:45:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
543552,2022-2023,1778469,NaN,1751,L643,Heavy Traffic,"15032,15628,15689,15704",12/16/2022 07:21:00 AM,12/16/2022 07:23:00 AM,Brooklyn,...,31-45 Min,2,No,No,No,12/16/2022 07:23:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age

In [5]:
#Sum Null in Run_Type
final_df['Run_Type'].isnull().sum()

0

In [4]:
#Removing rows with null in Runtype
final_df.dropna(subset=['Run_Type'], inplace=True)
len(final_df.index)

545685

In [7]:
#Check Values in Boro column
pd.unique(final_df['Boro'])

array(['New Jersey', 'Manhattan', 'Bronx', 'Westchester', 'Brooklyn',
       'Rockland County', 'Nassau County', nan, 'Queens', 'Staten Island',
       'All Boroughs', 'Connecticut'], dtype=object)

In [6]:
#Check null(nan) in Boro column
final_df['Boro'].isnull().sum()

11217

In [8]:
#Replace the null to values in Boro column
final_df['Boro'].fillna('unspecified', inplace=True)
pd.unique(final_df['Boro'])

array(['New Jersey', 'Manhattan', 'Bronx', 'Westchester', 'Brooklyn',
       'Rockland County', 'Nassau County', 'unspecified', 'Queens',
       'Staten Island', 'All Boroughs', 'Connecticut'], dtype=object)

In [9]:
pd.unique(final_df['Boro'])

array(['New Jersey', 'Manhattan', 'Bronx', 'Westchester', 'Brooklyn',
       'Rockland County', 'Nassau County', 'unspecified', 'Queens',
       'Staten Island', 'All Boroughs', 'Connecticut'], dtype=object)

In [10]:
#Check null data in all file
final_df.isna().any()
#true = null

School_Year                        False
Busbreakdown_ID                    False
Run_Type                           False
Bus_No                              True
Route_Number                        True
Reason                              True
Schools_Serviced                    True
Occurred_On                        False
Created_On                         False
Boro                               False
Bus_Company_Name                   False
How_Long_Delayed                    True
Number_Of_Students_On_The_Bus      False
Has_Contractor_Notified_Schools    False
Has_Contractor_Notified_Parents    False
Have_You_Alerted_OPT               False
Informed_On                        False
Incident_Number                     True
Last_Updated_On                    False
Breakdown_or_Running_Late          False
School_Age_or_PreK                 False
dtype: bool

In [11]:
#change datatypes to datetime
final_df['Occurred_On']=pd.to_datetime(final_df['Occurred_On'])
final_df['Created_On'] = pd.to_datetime(final_df['Created_On'])
final_df['Informed_On'] = pd.to_datetime(final_df['Informed_On'])
final_df['Last_Updated_On'] = pd.to_datetime(final_df['Last_Updated_On'])

final_df.dtypes

School_Year                                object
Busbreakdown_ID                             int64
Run_Type                                   object
Bus_No                                     object
Route_Number                               object
Reason                                     object
Schools_Serviced                           object
Occurred_On                        datetime64[ns]
Created_On                         datetime64[ns]
Boro                                       object
Bus_Company_Name                           object
How_Long_Delayed                           object
Number_Of_Students_On_The_Bus               int64
Has_Contractor_Notified_Schools            object
Has_Contractor_Notified_Parents            object
Have_You_Alerted_OPT                       object
Informed_On                        datetime64[ns]
Incident_Number                            object
Last_Updated_On                    datetime64[ns]
Breakdown_or_Running_Late                  object
School_Age_or_PreK                         object
dtype: object

In [53]:
final_df['School_Year'].value_counts()

2018-2019    109059
2021-2022     70179
2019-2020     65998
2020-2021     20438
Name: School_Year, dtype: int64

In [36]:
#Test count rows with the non-use rows
#final_df.drop(["2016-2017","2017-2018","2022-2023"])
df_filter=final_df[final_df['School_Year']=='2016-2017']
print(df_filter.shape)
df_filter2=final_df[final_df['School_Year']=='2017-2018']
print(df_filter2.shape)
df_filter3=final_df[final_df['School_Year']=='2022-2023']
print(df_filter3.shape)

(83141, 21)
(89435, 21)
(44257, 21)

In [52]:
#Remove rows with the non-use rows
final_df=final_df[final_df["School_Year"].str.contains("2015-2016")==False]
final_df=final_df[final_df["School_Year"].str.contains("2016-2017|2017-2018|2022-2023")==False]
final_df.head(-2)

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
82,2018-2019,1456627,General Ed AM Run,1141,R1086,Heavy Traffic,31051,09/05/2018 07:28:00 AM,09/05/2018 07:29:00 AM,Staten Island,...,31-45 Min,0,Yes,No,No,09/05/2018 07:29:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
835,2018-2019,1456628,Special Ed AM Run,87D,X966,Mechanical Problem,"12006,12009,12134,12314",09/05/2018 07:10:00 AM,09/05/2018 07:29:00 AM,Bronx,...,NaN,0,Yes,Yes,No,09/05/2018 07:29:00 AM,NaN,01/01/1900 12:00:00 AM,Breakdown,School-Age
2238,2018-2019,1456629,Special Ed AM Run,1140,X174,Heavy Traffic,"10003,10118",09/05/2018 07:27:00 AM,09/05/2018 07:29:00 AM,Bronx,...,16-30 Min,3,Yes,No,No,09/05/2018 07:29:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
3793,2018-2019,1456630,Special Ed AM Run,5591,Q059,Heavy Traffic,27210,09/05/2018 07:29:00 AM,09/05/2018 07:30:00 AM,Queens,...,31-45 Min,0,Yes,Yes,Yes,09/05/2018 07:30:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
5001,2018-2019,1456631,Special Ed AM Run,1505,K042,Other,"22109,22446,22790",09/05/2018 06:30:00 AM,09/05/2018 07:30:00 AM,Brooklyn,...,46-60 Min,0,No,No,No,09/05/2018 07:30:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502480,2018-2019,1564211,Pre-K/EI,9061,3112A,Other,C117,06/21/2019 07:00:00 AM,06/21/2019 07:23:00 AM,Brooklyn,...,46-60 Min,0,Yes,Yes,Yes,06/21/2019 07:23:00 AM,NaN,06/21/2019 09:54:16 AM,Running Late,Pre-K
502481,2018-2019,1564527,Special Ed AM Run,1627D,X750,Mechanical Problem,11458,06/24/2019 06:43:00 AM,06/24/2019 06:46:00 AM,Bronx,...,NaN,0,Yes,No,No,06/24/2019 06:46:00 AM,NaN,01/01/1900 12:00:00 AM,Breakdown,School-Age
502482,2018-2019,1565307,Special Ed PM Run,1104,M792,Heavy Traffic,"02350,02632",06/26/2019 02:07:00 PM,06/26/2019 02:08:00 PM,Manhattan,...,46-60 Min,0,Yes,Yes,No,06/26/2019 02:08:00 PM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
502483,2018-2019,1565308,Special Ed PM Run,651,L655,Delayed by School,"13369,15628,15689,15704",06/26/2019 02:15:00 PM,06/26/2019 02:45:00 PM,Brooklyn,...,0-15 Min,0,Yes,Yes,No,06/26/2019 02:45:00 PM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
502484,2018-2019,1565309,Pre-K/EI,9311,8,Heavy Traffic,E219,06/26/2019 02:48:00 PM,06/26/2019 02:51:00 PM,Bronx,...,16-30 Min,0,Yes,Yes,No,06/26/2019 02:51:00 PM,NaN,01/01/1900 12:00:00 AM,Running Late,Pre-K